question_data = [
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The S in Harry S. Truman stands for 'Samuel'.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "There was a satirical candidate named 'Deez Nuts' running in the 2016 US presidential elections.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "In 2016, the United Kingdom voted to stay in the EU.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Denmark has a monarch.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Despite being seperated into multiple countries, The Scandinavian countries are unified by all having the same monarch.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "The 2016 United States Presidential Election is the first time Hillary Clinton has run for President.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "One of Barack Obama&#039;s United States presidential campaign slogan&#039;s was 'Yes We Can'.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Donald Trump won the popular vote in the 2016 United States presidential election.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "category": "Politics",
                "type": "boolean",
                "difficulty": "easy",
                "question": "Former president Theodore Roosevelt (1900-1908)  ran for another term under the Progressive Party in 1912.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            }
]
